---
# tasks file for update
#
#
#
# Incluir variables del archivo de variables
## Instalar Epel para que cargue la variable de "RedHat"
  - name: Incluir variables
    include_vars: /root/.ssh/GitTaller/roles/update/vars/main.yml

  - name: Actualizar paquetes en Red Hat
    dnf:
      name: "*"
      state: latest
      update_only: yes
    when: ansible_os_family in ['RedHat', 'Rocky']
    notify: Reiniciar servidor

  - name: Actualizar paquetes en Debian
    apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"
    notify: Reiniciar servidor


  - name: Instalar Epel en Rocky
    dnf:
      name: epel-release
      state: latest
    when: ansible_os_family in ['RedHat', 'Rocky']

  - name: Firewall activado con ssh habilitado en Debian
    ufw:
      state: enabled
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop: "{{ port_debian }}"
    when: ansible_os_family == "Debian"

  - name: Firewall activado con ssh habilitado en RedHat
    firewalld:
      permanent: yes
      state: enabled
      port: "{{ item }}"
    loop: "{{ port_redhat }}"
    when: ansible_os_family in ['RedHat', 'Rocky']


  - name: Instalar paquetes en RedHat
    dnf:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop: "{{ paquetes_rh }}"
    when: ansible_os_family in ['RedHat', 'Rocky']

  - name: Instalar paquetes en Debian
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop: "{{ paquetes_deb }}"
    when: ansible_os_family == "Debian"




