---
# vars file for update


paquetes_rh:
- httpd
- java-17-openjdk
- mariadb-server
- mariadb
- tar
- python3-libselinux
- python3-libsemanage
- policycoreutils-python-utils

paquetes_deb:
- apache2
- openjdk-17-jdk
- mariadb-server
- mariadb-client
- python3-libselinux
- python3-libsemanage
- policycoreutils-python-utils

port_ubuntu:
- 22

port_redhat:
- 22/tcp

