---
# tasks file for dbserver
#
  - name: Incluir variables
    include_vars: /home/sysadmin/GitTaller/roles/dbserver/vars/main.yml

    #Tareas comunes:

  - name: Iniciar MySql en RedHat
    service:
      name: mysqld
      enabled: true
      state: started
    when: ansible_os_family in ['RedHat', 'Rocky']

  - name: Iniciar MariaDB en Debian
    service:
      name: mariadb
      enabled: true
      state: started
    when: ansible_os_family == "Debian"

  - name: RedHat - Permitir conexiones a mysql - SELinux
    seboolean: name=mysql_connect_any state=true persistent=yes
    when: ansible_os_family in ['RedHat', 'Rocky']

# Se inicializan y habilitan servicios MySQL
#### RedHat ####
  - name: RedHat - Iniciar y habilitar MySQL
    service: name=mysqld state=started enabled=yes
    when: ansible_os_family in ['RedHat', 'Rocky']

  #### Debian ####
  - name: Debian - Iniciar y habilitar MySQL
    service: name=mysql state=started enabled=yes
    when: ansible_facts['os_family'] == "Debian"

# Creacion de reglas de firewall para funcionamiento de MariaDB
  #### RedHat ####
  - name: RedHat - Creacion regla de firewalld MariaDB
    firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
    when: ansible_os_family in ['RedHat', 'Rocky']

#### Debian ####
  - name: Debian - Creacion regla de firewall MySQL
    ufw:
      rule: allow
      port: "{{ mysql_port }}"
      proto: tcp
    when: ansible_facts['os_family'] == "Debian"

# Creacion de usuario de base de datos
#### RedHat ####
  - name: RedHat - Crear usuario en DB
    mysql_user:
      name: "{{ dbuser }}"
      password: "{{ userpasswd }}"
      priv: '{{ dbname }}.*:ALL,GRANT'
      state: present
    when: ansible_os_family in ['RedHat', 'Rocky']

#### Debian ####
  - name: Debian - Crear usuario en DB
    mysql_user:
      name: "{{ dbuser }}"
      password: "{{ userpasswd }}"
      priv: '{{ dbname }}.*:ALL,GRANT'
      state: present
    when: ansible_facts['os_family'] == "Debian"

# Creacion y configuracion de base de datos

#### RedHat ####
  - name: RedHat - Crear DB de aplicacion
    mysql_db:      
      name: "{{ dbname }}"
      state: present
    when: ansible_os_family in ['RedHat', 'Rocky']

#### Debian ####
  - name: Debian - Crear DB de aplicacion
    mysql_db:
      name: "{{ dbname }}"
      state: present
      # login_password: "{{ dbpassword }}"
    when: ansible_facts['os_family'] == "Debian"



# Creación de tablas de la base de datos de la aplicación

#### RedHat ####
  - name: Mover archivo creacion de tablas todo.sql
    template:
      src: todo.sql
      dest: /tmp/todo.sql
    when: ansible_os_family in ['RedHat', 'Rocky']

  - name: RedHat - Crear tabla DB de aplicacion
    mysql_db: name=todo state=import target=/tmp/todo.sql
    when: ansible_os_family in ['RedHat', 'Rocky']

#### Debian ####
  - name: Mover archivo creacion de tablas todo.sql
    template:
      src: todo.sql
      dest: /tmp/todo.sql
    when: ansible_facts['os_family'] == "Debian"

  - name: Debian - Crear tabla DB de aplicacion
    mysql_db: name=todo state=import target=/tmp/todo.sql
    when: ansible_facts['os_family'] == "Debian"


    # Eliminacion de usuario anonimo 
#### Debian ####
  - name: Debian - Eliminar usuario anonimo
    no_log: true
    mysql_user:  
      name: ''
      host: localhost
      state: absent
    when: ansible_facts['os_family'] == "Debian"  

  #### RedHat ####
  - name: RedHat - Eliminar usuario anonimo
    no_log: true
    mysql_user:      
      name: ''
      host_all: True
      state: absent
    when: ansible_os_family in ['RedHat', 'Rocky']
