---
# tasks file for webserver
#
  - name: Incluir variables
    include_vars: /root/.ssh/GitTaller/roles/webserver/vars/main.yml

  - name: Firewall activar puerto 80
    firewalld:
      permanent: yes
      port: "{{ item }}"
      state: enabled
    loop: "{{ port_redhat }}"
    when: ansible_os_family in ['RedHat', 'Rocky']

  - name: Firewall activar puerto 80
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
      state: enabled
    loop: "{{ port_ubuntu }}"
    when: ansible_os_family == "Debian"

# Configuracion de SELinux para conexiones entre apache y mysql - RedHat
  - name: RedHat - Permitir a httpd conectar con mysql
    seboolean:
      name: httpd_can_network_connect_db
      persistent: yes
      state: yes
    when: ansible_os_family in ['RedHat', 'Rocky']

  - name: Configuración Proxy Reverso RedHat
    template:
      src: default-site.conf
      dest: /etc/httpd/conf.d/default-site.conf
    when: ansible_os_family in ['RedHat', 'Rocky']  
    notify: Reiniciar servicio httpd

    
  - name: Configuración Proxy Reverso Debian
    template:
      src: default-site.conf
      dest: /etc/apache2/sites-available/Apache2Proxy.conf
    when: ansible_os_family in ['Debian']  
    notify: Reiniciar servicio apache

 
